# NexT Theme Configuration Override
# See: https://theme-next.js.org/docs/getting-started/configuration

# Scheme
scheme: Gemini

# Dark Mode
darkmode: true

# Menu
menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive

menu_settings:
  icons: true
  badges: false

# Sidebar
sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

avatar:
  rounded: true
  rotated: false

# Social Links
social:
  GitHub: https://github.com/cenjing || fab fa-github

social_icons:
  enable: true
  icons_only: false
  transition: false

# Footer
footer:
  since: 2026
  icon:
    name: fa fa-heart
    animated: false
    color: "#ff0000"
  powered: true

# Post
post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true

# Code block
codeblock:
  theme:
    light: default
    dark: stackoverflow-dark
  copy_button:
    enable: true
    style: flat
  language: true

# Back to top
back2top:
  enable: true
  sidebar: false
  scrollpercent: true

# Reading progress
reading_progress:
  enable: true
  start_at: left
  position: top
  color: "#37c6c0"
  height: 3px

# GitHub banner
github_banner:
  enable: false

# Local Search
local_search:
  enable: false
  top_n_per_article: 1
  unescape: false
  preload: false
